# Q-->1:Create a numpy array starting from 2 till 50 with a stepsize of 3.


In [2]:
import numpy as np
# numpy .arange ( start, end , steps)
np.arange(2,51,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

# Q-->2: Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.


In [3]:
import numpy as np
#two lists of 5 elements each taken  from user

lst_1=[]
lst_2=[]
#Given 5 elements to accept for each list from user
for i in range(5):
    #Accepting 5 elements for lst_1
    n1=int(input())
    #Adding the user input to lst_1
    lst_1.append(n1)
for j in range(5):
    #Accepting 5 elements for lst_2
    n2=int(input())
    #Adding the user input to lst_2
    lst_2.append(n2)
#Displaying the lists
print(lst_1)
print(lst_2)

#Converting list into numpy arrrays
array1=np.array(lst_1)
array2=np.array(lst_2)

#Concatenating arrays
array3=np.concatenate((array1,array2))
print(array3)
#Sorting arrays
print(np.sort(array3))

1
3
5
7
8
9
12
3
4
54
[1, 3, 5, 7, 8]
[9, 12, 3, 4, 54]
[ 1  3  5  7  8  9 12  3  4 54]
[ 1  3  3  4  5  7  8  9 12 54]


# Q--> 3:Write a code snippet to find the dimensions of a ndarray and its size.


In [6]:
import numpy as np
 
# Creating array object
arr = np.array( [[ 19, 22, 13, 87],
                 [ 42, 45, 34, 31]] )

# Printing array dimensions
print("No. of dimensions: ", arr.ndim)
 
# Printing shape of array
print("Shape of array: ", arr.shape)
 
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)

No. of dimensions:  2
Shape of array:  (2, 4)
Size of array:  8


# Q -->4: Convert a 1D array into a 2D array with the help of a code snippet Hint: np.newaxis, np.expand_dims


In [7]:
import numpy as np

arr = np.arange(int(input()))
print("Test 1D array (shape) :",arr.shape)

two_d_array_row = arr[np.newaxis]
print("Test 2D array for row is :",two_d_array_row.shape)

two_d_array_column = arr[:, np.newaxis]
print("Test 2D array for column is :",two_d_array_column.shape)


65
Test 1D array (shape) : (65,)
Test 2D array for row is : (1, 65)
Test 2D array for column is : (65, 1)


# Q-->5: Consider two square numpy arrays. Stack them vertically and horizontally. Hint: Use vstack(), hstack()


In [8]:
import numpy as np
array1 = np.array([[2, 6, 8], [4, 36, 64]])
array2 = np.array([[77, 56, 87], [11, 121, 81]])
 
# Stack arrays in sequence horizontally

print("Horizontally stacked:")
arrayH = np.hstack((array1, array2))
print(arrayH)
 
print("-" * 20)
 
# Stack arrays in sequence vertically 

print("Vertically stacked")
arrayV = np.vstack((array1, array2))
print(arrayV)
 
print("-" * 20)

Horizontally stacked:
[[  2   6   8  77  56  87]
 [  4  36  64  11 121  81]]
--------------------
Vertically stacked
[[  2   6   8]
 [  4  36  64]
 [ 77  56  87]
 [ 11 121  81]]
--------------------


# Q -->6:Write a program to get unique items and counts of unique items


In [9]:
import numpy as np
arr=np.array([2,3,4,5,6,7,89,2,3,4,5,6,7,8,9,2,3,4,4,6,7,7,7,8,8,9,])

unique,counts=np.unique(arr,return_counts=True)
arr=np.asarray((unique,counts)).T
print(arr)

[[ 2  3]
 [ 3  3]
 [ 4  4]
 [ 5  2]
 [ 6  3]
 [ 7  5]
 [ 8  3]
 [ 9  2]
 [89  1]]
